// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQplUMRRJ7aFV9ukwWrY30ThpUeXWnPJc',
    appId: '1:729043734296:web:8512c459b3823d7c37186d',
    messagingSenderId: '729043734296',
    projectId: 'onlycats-f8446',
    authDomain: 'onlycats-f8446.firebaseapp.com',
    storageBucket: 'onlycats-f8446.firebasestorage.app',
    measurementId: 'G-G9HX50B028',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqnnuPZBsx_nnsVoiVwt2hRXFUoN58P3s',
    appId: '1:729043734296:android:925ea198516f288737186d',
    messagingSenderId: '729043734296',
    projectId: 'onlycats-f8446',
    storageBucket: 'onlycats-f8446.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM7v3qGe0tXUNegSaW-_ZaVL_Y6wqilLY',
    appId: '1:729043734296:ios:e30c848943154b9a37186d',
    messagingSenderId: '729043734296',
    projectId: 'onlycats-f8446',
    storageBucket: 'onlycats-f8446.firebasestorage.app',
    iosBundleId: 'com.example.onlycats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM7v3qGe0tXUNegSaW-_ZaVL_Y6wqilLY',
    appId: '1:729043734296:ios:e30c848943154b9a37186d',
    messagingSenderId: '729043734296',
    projectId: 'onlycats-f8446',
    storageBucket: 'onlycats-f8446.firebasestorage.app',
    iosBundleId: 'com.example.onlycats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQplUMRRJ7aFV9ukwWrY30ThpUeXWnPJc',
    appId: '1:729043734296:web:6f99223f6d84812c37186d',
    messagingSenderId: '729043734296',
    projectId: 'onlycats-f8446',
    authDomain: 'onlycats-f8446.firebaseapp.com',
    storageBucket: 'onlycats-f8446.firebasestorage.app',
    measurementId: 'G-5T045SKSKN',
  );
}
